export const ApplicationFields = [
  "application_id",
  "certificate_reference",
  "loss_country",
  "loss_year",
  "loss_month",
  "loss_day",
  "print_date_of_loss",
  "loss_placename",
  "baby_sex",
  "baby_name",
  "application_address_line_1",
  "application_address_line_2",
  "application_address_line_3",
  "application_address_line_4",
  "application_address_line_5",
  "application_address_postcode",
  "created_dtm",
  "created_by",
  "version",
  "applicant_parent_id",
  "second_parent_id",
  "application_status",
  "send_on_second_parent_reject",
  "application_reference_number",
  "multiloss_certificate_number",
  "multiloss_identifier",
];

export const ParentFields = [
  "parent_id",
  "parent_reference_number",
  "parent_reference_type",
  "parent_reference_number_issuing_country",
  "parent_given_name",
  "parent_family_name",
  "parent_relationship",
  "parent_date_of_birth",
  "parent_email_address",
  "created_dtm",
  "created_by",
  "application_id",
  "parent_number",
];

export const IncompleteParentFields = [
  "parent_id",
  "parent_reference_number",
  "parent_reference_type",
  "parent_reference_number_issuing_country",
  "parent_relationship",
  "parent_date_of_birth",
  "parent_email_address",
  "created_dtm",
  "created_by",
  "application_id",
  "parent_number",
];

export const DefaultValues = {
  parentReferenceNumber: "Not provided",
  parentReferenceType: 11,
  parentReferenceNumberIssuingCountry: "000",
  firstParentNumber: 1,
  secondParentNumber: 2,
};
